import { Sandbox } from "e2b";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import {
  StateGraph,
  Annotation,
  messagesStateReducer,
} from "@langchain/langgraph";
import { ToolNode } from "@langchain/langgraph/prebuilt";
import {
  BaseMessage,
  HumanMessage,
  SystemMessage,
} from "@langchain/core/messages";

import { LLM_TOKEN } from "../env";
import { octokit } from "../github/octokit";
import { linearClient } from "../linear/client";
import { getLangchainGithubTools } from "../agent/tools";
import {
  getGithubRepoUrl,
  appendGithubToken,
  parseOwnerRepo,
  AI_MODEL,
  REPO_PATH,
} from "../shared";

/**
 * Runs the full AI agent workflow inside a sandboxed environment.
 *
 * Assumes the caller has already:
 * 1. Validated the webhook payload
 * 2. Acquired the distributed lock (ai-in-progress label)
 * 3. Confirmed idempotency (no duplicate in-progress/done/failed labels)
 *
 * This function owns the Sandbox lifecycle (create → kill).
 */
export async function runAgentWorkflow(
  issue: { id: string; title: string; description: string; projectId: string },
  labels: {
    aiInProgressLabelId: string;
    aiDoneLabelId: string;
    aiFailedLabelId: string;
  }
) {
  console.log("📦 Creating sandbox...");
  const sandbox = await Sandbox.create();

  try {
    console.log("⬇️ Cloning repo...");
    const repoUrl = await getGithubRepoUrl(issue.projectId);

    await sandbox.commands.run(
      `git clone ${appendGithubToken(repoUrl)} ${REPO_PATH}`
    );
    await sandbox.commands.run(
      `git config --global user.email "ai@linear.app" && git config --global user.name "AI Agent"`,
      { cwd: REPO_PATH }
    );

    console.log("🛠 Initializing Agent...");
    const tools = getLangchainGithubTools(sandbox, repoUrl);
    const model = new ChatGoogleGenerativeAI({
      model: AI_MODEL,
      apiKey: LLM_TOKEN,
    }).bindTools(tools);

    const AgentState = Annotation.Root({
      messages: Annotation<BaseMessage[]>({ reducer: messagesStateReducer }),
    });
    const workflow = new StateGraph(AgentState)
      .addNode("agent", async (state) => ({
        messages: [await model.invoke(state.messages)],
      }))
      .addNode("tools", new ToolNode(tools))
      .addEdge("__start__", "agent")
      .addConditionalEdges("agent", (state) => {
        const last = state.messages[state.messages.length - 1] as any;
        return last.tool_calls?.length > 0 ? "tools" : "__end__";
      })
      .addEdge("tools", "agent");

    const app = workflow.compile().withConfig({ recursionLimit: 25 });

    // ── Run agent loop ──────────────────────────────────────────
    console.log("🧠 Running Agent loop...");
    await app.invoke({
      messages: [
        new SystemMessage(`You are a Senior Software Engineer.
            YOUR PROCESS:
            1. EXPLORE: Use 'getProjectResources' and 'listFiles'.
            2. READ: Use 'getFileContent'.
            3. WRITE: Use 'writeFile' to apply changes.
            - Once changes are done, output "TASK_COMPLETE".`),
        new HumanMessage(
          `Issue: ${issue.title}\nDescription: ${issue.description}`
        ),
      ],
    });
    console.log("✅ Agent loop finished.");

    const branchName = `ai-fix-${issue.id}-${Date.now()}`;
    console.log(`🌿 Branching: ${branchName}`);
    await sandbox.commands.run(`git checkout -b ${branchName}`, {
      cwd: REPO_PATH,
    });

    const status = await sandbox.commands.run("git status --porcelain", {
      cwd: REPO_PATH,
    });

    if (status.stdout.trim() !== "") {
      console.log("💾 Committing and Pushing...");

      // Write commit message to a file to avoid shell injection via issue.title
      const commitMsg = `AI Fix: ${issue.title}`;
      await sandbox.files.write(`${REPO_PATH}/.git/COMMIT_MSG`, commitMsg);

      await sandbox.commands.run("git add .", { cwd: REPO_PATH });
      await sandbox.commands.run(`git commit -F .git/COMMIT_MSG`, {
        cwd: REPO_PATH,
      });
      await sandbox.commands.run(`git push origin ${branchName}`, {
        cwd: REPO_PATH,
      });

      const { owner, repo } = parseOwnerRepo(repoUrl);

      const { data: repoData } = await octokit.rest.repos.get({
        owner,
        repo,
      });

      await octokit.rest.pulls.create({
        owner,
        repo,
        title: `AI Fix: ${issue.title}`,
        body: `Automated PR generated by AI. \n\nRelated Issue: ${issue.title}`,
        head: branchName,
        base: repoData.default_branch,
        draft: true,
      });
      console.log("🎉 PR Created.");
    }

    // ── Mark done ───────────────────────────────────────────────
    await linearClient.updateIssue(issue.id, {
      addedLabelIds: [labels.aiDoneLabelId],
      removedLabelIds: [labels.aiInProgressLabelId],
    });
  } catch (error) {
    console.error("❌ Agent error:", error);
    try {
      await linearClient.updateIssue(issue.id, {
        addedLabelIds: [labels.aiFailedLabelId],
        removedLabelIds: [labels.aiInProgressLabelId],
      });
    } catch (labelError) {
      console.error(
        "❌ Failed to mark issue as ai-failed (issue may be stuck as ai-in-progress):",
        labelError
      );
    }
  } finally {
    await sandbox.kill();
  }
}
